# Generated by Django 3.2a1 on 2021-02-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Bark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('content', models.CharField(max_length=160)),
                ('views', models.IntegerField(default=0)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackdog.dog')),
            ],
        ),
    ]
