# Generated by Django 3.2a1 on 2021-02-07 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackdog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bark',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='bark',
            name='reporter',
        ),
        migrations.AddField(
            model_name='bark',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
